---
- name: "Kuma health check {{ lxc_id }}"
  uri:
    url: "{{ kuma_url }}/api/status-page/heartbeat/{{ kuma_slug | default('unknown') }}"
    method: GET
  delegate_to: localhost
  register: kuma_json
  until: "(kuma_json.json.heartbeatList[lxc_kuma_map[lxc_id] | string] | last).status == 1 or ansible_check_mode"
  retries: 5
  delay: 30
  when:
    - lxc_id in lxc_kuma_map
    - ansible_check_mode or (app_update_res is defined and app_update_res.changed) or (os_update_res is defined and os_update_res.changed)
  ignore_errors: yes
