---
driver:
  name: default
  options:
    managed: false

platforms:
  - name: localhost

provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        hosts:
          localhost:
            ansible_connection: local
  playbooks:
    converge: converge.yml
    verify: verify.yml

verifier:
  name: ansible
